"""init

Revision ID: 4b0176372f2e
Revises: 
Create Date: 2024-06-18 04:27:07.271404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4b0176372f2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('src', sa.String(length=255), nullable=True),
                    sa.Column('description', sa.String(length=200), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_memes_id'), 'memes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memes_id'), table_name='memes')
    op.drop_table('memes')
    # ### end Alembic commands ###
